const movies = [
  "Shawshank Redemption",
  "Pulp Fiction",
  "The Dark Knight",
  "Fight Club",
  "Matrix",
  "Goodfellas",
  "Inception",
  "Lord",
  "Avengers",
  "Star Wars",
  "Titanic",
  "Jurassic Park",
  "Lion King",
  "Back to the Future",
  "Social Network",
  "La La Land",
  "Interstellar",
  "Silence of the Lambs",
  "The Departed",
  "Gladiator",
  "Casablanca",
  "Wizard of Oz",
  "Gone with the Wind",
  "Inglourious Basterds",
  "Redemption",
  "Dark Knight Rises",
  "Green",
  "Godfather",
  "Great Gatsby",
  "Prestige",
  "Eternal Sunshine of the Spotless Mind",
  "Truman",
  "Suspects",
  "Sixth Sense",
  "Social Network",
  "Drive",
  "Mad Max",
  "Revenant",
  "Whiplash",
  "Grand Budapest Hotel",
  "Birdman",
  "Her",
  "Blade Runner 2049",
  "Get Out",
  "Black Panther",
  "The Shape of Water",
  "La La Land",
  "Moonlight",
  "Parasite",
  "Joker",
  "Once Upon a Time in Hollywood",
  "Tenet",
  "Soul",
];

const series = [
  "Friends",
  "Breaking",
  "Stranger Things",
  "Thrones",
  "Office",
  "Sherlock",
  "Black Mirror",
  "Crown",
  "Big Bang",
  "Friends",
  "Simpsons",
  "Lost",
  "Dead",
  "Narcos",
  "Break",
  "Witcher",
  "Mindhunter",
  "Westworld",
  "Heist",
  "Blinders",
  "Mandalorian",
  "Stranger Things",
  "Breaking Bad",
  "Vikings",
  "Detective",
  "House",
  "Better",
  "Tale",
  "Dexter",
  "Mother",
  "Fargo",
  "House of Cards",
  "Friends",
  "The Office",
  "Game of Thrones",
  "Stranger Things",
  "Breaking Bad",
  "Sherlock",
  "Black Mirror",
  "Crown",
  "Bang",
  "Walking Dead",
  "Narcos",
  "Break",
  "Witcher",
  "Westworld",
  "Money",
  "Blinders",
  "Mandalorian",
  "Better",
  "Tale",
  "Dexter",
  "Mother",
  "Fargo",
  "Cards",
  "Detective",
  "Hill",
  "Vikings",
  "Simpsons",
  "Lost",
];

const randomIndex = Math.floor(Math.random() * movies.length);

export const randomMovie = movies[randomIndex];

export const randomShow = series[randomIndex];
